import type { Metadata } from "next";

import { Kanit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProviders";

const kanit = Kanit({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${kanit.variable}`} suppressHydrationWarning>
      <body className="font-kanit">
        <ThemeProvider attribute="class" defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
